### ISSUE TITLE
The countries api it’s not working

### ISSUE THREAD

**Issue by mncfre** [NovelCOVID/API#36]
The countries api show an empty json

**Comment by thenamesweretakenalready** [comment]
#30

**Comment by silverhairs** [comment]
> The countries api show an empty json

Fixed

**Comment by gitmonox** [comment]
Is not fixed. the cases are diferent from the source
Array

"country": "Brazil",
"cases": 203,
"todayCases": 3,
"deaths": 0,
"todayDeaths": 0,
"recovered": 2,
"critical": 2

source
Brazil | 367 | +21 | 1
-- | -- | -- | --

**Comment by EliteDaMyth** [comment]
Fixed
